### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by djdta** [djdta/Service-Registry#2]
## Description:
Currently, there is no folder or code in this folder at this moment.  Looking to design out a folder structure for this folder with the ability to make it easy to use.

## Techincal Requirements:
- [x] CIS Benchmark scripts to apply to newly created packer images
- [x] To run CIS level 1 image on deployed services and infrastructure.
- [x] The ability to run checks,
- [x] Support for Windows, Linux

## Design:
- [x] #4

## Implemention:
- [x] #5
 
## Approved:
- [x] #6

**Comment by djdta** [comment]
Epic Resolve as all tasks have been completed
